version: '3'

services:
  api:
    container_name: ra-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - '3001:3001'
    volumes:
      - ./:/usr/src/ra-api
      - /usr/src/ra-api/node_modules
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - '5432:5432'
    volumes:
      - ra_postgres:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

volumes:
  ra_postgres:
